[package]
name = "cefdetector"
version = "0.3.0"
description = "Check how many CEFs are on your Linux."
authors = ["Origuchi"]
license = "MIT"
repository = "https://github.com/Tobiichi-Origuchi/CefDetectorLinux"
edition = "2024"
rust-version = "1.92.0"

[dependencies]
pelite = "0.10.0"
ignore = "0.4.31"
memchr = "2.8.3"
memmap2 = "0.9.11"
backhand = { version = "0.25.1", default-features = false, features = ["gzip", "lz4", "xz", "zstd"] }
image = { version = "0.25.10", default-features = false, features = ["png", "ico", "webp"] }
egui = { version = "0.35.0", default-features = false }
egui_glow = { version = "0.35.0", default-features = false, features = ["wayland", "winit", "x11"] }
glutin = { version = "0.32.3", default-features = false, features = ["egl", "glx", "wayland", "x11"] }
glutin-winit = { version = "0.5.0", default-features = false, features = ["egl", "glx", "wayland", "x11"] }
resvg = { version = "0.47.0", default-features = false }

[package.metadata.packager]
identifier = "cefdetector"
category = "Utility"
description = "Check how many CEFs are on your Linux."
homepage = "https://github.com/Tobiichi-Origuchi/CefDetectorLinux"
publisher = "Origuchi"
icons = ["icons/32x32.png", "icons/128x128.png", "icons/128x128@2x.png", "icons/icon.icns", "icons/icon.ico"]
formats = ["deb", "pacman"]
out-dir = "target/release/packager"
before-packaging-command = "cargo build --locked --release"

[package.metadata.packager.deb]
depends = ["fontconfig", "libegl1 | libglx0", "xdg-utils"]
package-name = "cefdetector"
section = "utils"
files = { "completions/cefdetector.bash" = "/usr/share/bash-completion/completions/cefdetector", "completions/cefdetector.zsh" = "/usr/share/zsh/vendor-completions/_cefdetector", "completions/cefdetector.fish" = "/usr/share/fish/vendor_completions.d/cefdetector.fish" }

[package.metadata.packager.pacman]
depends = ["fontconfig", "libglvnd", "xdg-utils"]
provides = ["cefdetector"]
files = { "completions/cefdetector.bash" = "/usr/share/bash-completion/completions/cefdetector", "completions/cefdetector.zsh" = "/usr/share/zsh/vendor-completions/_cefdetector", "completions/cefdetector.fish" = "/usr/share/fish/vendor_completions.d/cefdetector.fish" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
