complete -c cefdetector -n "not __fish_seen_subcommand_from cli" -f -a cli -d "Run the command-line scanner"
complete -c cefdetector -n "not __fish_seen_subcommand_from cli" -s h -l help -d "Print help information"
complete -c cefdetector -n "not __fish_seen_subcommand_from cli" -s V -l version -d "Print version information"
complete -c cefdetector -n "not __fish_seen_subcommand_from cli" -l system-font -d "Use platform system fonts instead of embedded fonts"

complete -c cefdetector -n "__fish_seen_subcommand_from cli" -s h -l help -d "Print help information"
complete -c cefdetector -n "__fish_seen_subcommand_from cli" -s V -l version -d "Print version information"
complete -c cefdetector -n "__fish_seen_subcommand_from cli" -s T -l toml -d "Output results in TOML format"
complete -c cefdetector -n "__fish_seen_subcommand_from cli" -s J -l json -d "Output results in JSON format"
complete -c cefdetector -n "__fish_seen_subcommand_from cli" -s C -l csv -d "Output results in CSV format"
complete -c cefdetector -n "__fish_seen_subcommand_from cli" -s O -l output -r -F -d "Output results to the specified file path instead of stdout"
